name: Update Forex Real Time

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  update-realtime:
    runs-on: self-hosted
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          C:\Users\it-so\AppData\Local\Programs\Python\Python312\python.exe -m pip install MetaTrader5 pandas supabase python-dotenv
        continue-on-error: true
          
      - name: Update MT5 Data
        env:
          MT5_LOGIN: ${{ secrets.MT5_LOGIN }}
          MT5_PASSWORD: ${{ secrets.MT5_PASSWORD }}
          MT5_SERVER: ${{ secrets.MT5_SERVER }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          C:\Users\it-so\AppData\Local\Programs\Python\Python312\python.exe backend/mt5_data_downloader.py
        continue-on-error: true
